function D = AddNoiseUnits(d,n)
    subjects = unique(d.subject);
    examples = unique(d.example_id);
    
    [k,j,i] = ndgrid(1:n,examples,subjects);  
    subject = i(:);
    example_id = j(:);
    example_category = categorical(j(:) > 36, [0,1], {'A','B'});
    unit_category = categorical( ...
        ones(numel(k),1) * 7, ...
        1:8, ...
        {'SI','AI','SH','AH','SO','AO','noise','padding'}, ...
        'Ordinal',true);
    unit_id_by_category = k(:);
    unit_id = k(:) + max(unique(d.unit_id));
    unit_contribution = categorical(ones(numel(k),1),1,{'neither'});
    activation = zeros(numel(k), 1);
    
    e = table( ...
        subject, ...
        example_category, ...
        example_id, ...
        unit_category, ...
        unit_id, ...
        unit_id_by_category, ...
        unit_contribution, ...
        activation, ...
        'VariableNames',{
            'subject'
            'example_category'
            'example_id'
            'unit_category'
            'unit_id'
            'unit_id_by_category'
            'unit_contribution'
            'activation'
        });
        
	D = sortrows([d;e],1:7);
end
